[project]
name = "685"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rank-bm25>=0.2.2",
    "sentence-transformers>=5.2.0",
    "torch>=2.9.1",
]
